import { DineMarketContextProvider } from '@/DinemarketContex'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Asif Dine Market ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DineMarketContextProvider>
       <Navbar/>  
        {children}
       <Footer/>  
       </DineMarketContextProvider> 
        </body>
         

    </html>
  )
}
